dist: trusty
language: java
git:
  depth: 3
sudo: required
env: ' MAVEN_SETTINGS="${TRAVIS_BUILD_DIR}/gsi-config"  MAVEN_OPTS=''-Xms1g -Xmx2g''  SEQWARE_SETTINGS="${TRAVIS_BUILD_DIR}/seqware_settings" '

addons:
  sonarcloud:
    organization: "oicr-gsi"
    token: 
        secure: "rMeFydTZgp7i9s86jqARAhM+GXpfKiFKUsHKBoEMyJhMaFZCtu4+rW6Oy3drBRTlHBPfBjK8oZlFcB/FJMcOpDFDqRo72Io3vcnP3T6HPV/DNAwmYlpUYqbLVybORkhShiuh/PTHkLrjXuttSjbR3X+ypwbo4FwmmW6Q9AStrrPnYcfFpV0Eo8YpOOH4zy1NRBOVCeezu6ByblZw+E84xFp9IwSOv+G6qLq5LXFLYumb+5MwHDQk8Bo8MeVT5Jr4YMPX7rkeP+NjFHb/eSSjTpwDSf0rcvrFZ3KgYyMtHCN58gtk0WM0IIgJI8zhmvb3ZzzVuXkxjhs3e0WFWZ7nwEfMSWUAE1w/OBCSrm8hbuMkSHwlUMF8lLeCQp/bLgpfzI9+VCauV88+mRoI1zqbnCY41+zl78P6lVqABMcpGEJed4lzd0SUOgvXKLlOA4uKnTMVI1UyntYSUnR9pw6l8LYvn5CVVGoB2zk3tOV6tKkBFTuPrbI2/fKjygDFS/hulU9kyMZkts0rxIO1gd0W18r+LN6ttRJaH3L66PAdYFdL6d+f2rYnzAi076LP70GBFA5F93hzGTOWK3/60vvZ0EQiGGwzC5Yg6memUxMXLS6NJ/P/hK0QmCFDL3lNiLwyiuYE+0VNeX3M7PVmLOUaX9UUCU5/ur93WN1mAGPPgrM="
    github_token:
        secure: "TqaRhe7cqGWfZOz+WY/g2/018wICsCB/mBlQttsftcsspBYaWARDOlek2gScC5+S51IfUs5CB9i6OJm9tlwObR0QAx+i9cGYIkPN8tljgOhX+1eY5o5E5n5d7ntw4GsVLvz/8hZQ3hd9bZKzLH8ilw6q2Xtc/ZNOQL+dkLrOl84Q/lsfbOz3R9jGxdETYgkBPlk37M41xWzbA6k+xavp6Y0f+54ZeCTbhihetaKmYzmJLYPpBnKe1w6TIFYs9ZP4+/kj8yKQJkIPPNA5or1eFSfOiSkyBwGXG0UqJQHzHAfJZgL/J5C0SnVUiv04qZX3FFpuUQU/yNGQzSB+vH4xnb/Vbo8LxrCSSt9nCazEoY2Cpx8ZL/qw2owIWFHDmBpujtvO+hszgt96DA/RJNJ8wX4dA14raMLkPv1GtyqhFsy65PC/66hEnM46X8HCrm3gYAiX+kH07avx9xB2Be0aTDP/XBYDOpNmtu3rG0p69jyScUMXzUIGwtlTUpQaXsLkL/0h0pD+8ghhZYINh/Q14qlAk+T0IuUgp34XIaJE2jfQ8AFyo32b5ZWZvPDQ/Excj+2AsUBucmI9aE+Nr+oPY/k7VvFJvzck5opc1GsmvSDQ+VVzuW7Z3cT7pG3xeeWuHk13FBnfBzKMhTtq1gaCnGafe0eSl3wiJnjGLWKgFsM="


jdk:
- oraclejdk8

before_install:
- git clone https://github.com/oicr-gsi/gsi-config.git "${MAVEN_SETTINGS}"
- cp "${MAVEN_SETTINGS}/settings.xml" "${HOME}/.m2/settings.xml"

before_script:
- touch "${SEQWARE_SETTINGS}"

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
