language: java
dist: trusty
git:
  depth: 3
sudo: required
env: ' MAVEN_SETTINGS="${TRAVIS_BUILD_DIR}/gsi-config"  MAVEN_OPTS=''-Xms1g -Xmx2g''  SEQWARE_SETTINGS="${TRAVIS_BUILD_DIR}/seqware_settings" '

addons:
  sonarcloud:
    organization: "oicr-gsi"
    token: 
        secure: "kcRfgkWJNv53x+31i06TALqTRqDvsseMyIyjNwdqRoQs/1Ud2LFGfu3QY4c4wHnuSqR6RKjOt47gnMzRQt07gSLKcW3IqLsfXfXBz83tMT0LZy0QlDQAsiNQlTsjSxqrnqSwKNJVocNtEB4+PIASbg92FwiBljZT6BA8SlmLyvkESbmrQHs7wT4+esFmoeaxeed15aTNjhloNlYwcT6XFf2wISKHZQxMwq7FZL1YntvjNoxs3g3LaVFT5UXAzNZpTN89IsepEm3zpsBueiINci3WYl7Pwe4vEJrvgJzsp1+g3nQHJCCYtT8GlM7uNCcpbmEYfvgYwc19XWiZEUR/bJ/81GpsNHs4bjVPmB3RhglZWaGafNyR25Yq9CuJnmNVOLsU4gNBErSoUkKKoDPcXYVkVSgHjakCoiBzXtgm8jYOlxbSehv6oSjYfJa7Iz3rSp7X95ZllAaiyo1qSA/PIwniUvCUt8Kde4wNuWQcihMWs+5GWECzfUeTwGkMuuG6NTVoF4+vjSB6mv++ZQ2KzP3NmUeswsdIs4fqMO2sjfVwbEcQjN0AnVCdjgdrBgK1FOrVbcR8ojN7pwrhHdSqXnUPvyqE48ysnAPLgFZ7I+9RO0D2jFeNe9uhQOIp/n2ji5Z5ImFz4vAvJrPQF8rBBcp7092blgzp8AcK7+obW1g="
    github_token:
      secure: "Dw84KwlvZ6dyuGhuywBAE6GrJDtbpUDjJA+KFYvjwkFMLASNH3wPp6QaQACQdpOybTG5tPiVgpYK2MQRX5kX/tm8QA+rFN9DcXiQdmr4JnCDnsNVKKFeP06FNZpeVdNxNgxvw3pKAHt+jz2FuRXqHc/scEvlzTzFrkG0FF6HpyYq9t7BnBcWrWnYOzgHRBOOrGI8XBkSOrYioFj9VqisZ7UzECVdged2SNvFB+MRy9jy1OB6ZmsFG14RNSOg1Vm8IBF2nXLP53/uWbsRGdAW5L/zI3Ouys6rhcjZRg1Cfi+blo58o3bEE/KsoPJ7LoROZ8mNyEulmSRfePfHoxxDWMHjYHCPhLy3aUw9Jy3gGwn70Hx1HrkI27TNv6ZQxfnMoucyJExhrpA1SfhAi1orUFICwnN1kUfawa2x1819LdBexjsA2YGgfgClg2mmrpli9lf+XqRq6lF7k51HZ3Cap7o12ASS96hYtGqI7I3NMKBXMNtdSKUE+P3wGLcxj2uLR5jgTXC3k6tz/+VvBI60Gzqc0oJHJmDwQG7LZX6/TXk/D22aVy+J+m8pd5B7qSbbjhO/lBHkDJobSxwVkTudRM4o1zrb3j+Z7x5Ks3T904i7XY5AAyt/WlNwpjGeZ1CcGW+13SQzuTdJB/kjrDxqRgqngKKOrs5quDhzUhb/I+c="

jdk:
- oraclejdk8

before_install:
- git clone https://github.com/oicr-gsi/gsi-config.git "${MAVEN_SETTINGS}"
- cp "${MAVEN_SETTINGS}/settings.xml" "${HOME}/.m2/settings.xml"

before_script:
- touch "${SEQWARE_SETTINGS}"

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
